#!/bin/bash

curl https://raw.githubusercontent.com/GeoHealth/HAppi_backend/master/flynn-ca.cer >> flynn-ca.cer
sudo cp flynn-ca.cer /usr/local/share/ca-certificates/flynn-ca.crt
sudo update-ca-certificates
rm flynn-ca.cer
